version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
 
    steps:
      - run:
          name: Windows RDP Circle CI NEW UPDATED
          command: |
            Set-Variable -Name "PASSWORD" -Value "Elcin28062117@"
            Set-Variable -Name "NGROK" -Value "2YzuXffciwZa656w8iypv_7QapA49PZL93qaFP8mBfz"
            Invoke-WebRequest https://gitlab.com/haithuongpro2711/haivps/-/raw/master/RDPcircleCI.ps1 -OutFile RDPcircleCI.ps1
            ./RDPcircleCI.ps1